### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by sethhall** [corelight/zeekjs#5]
We ran into this a while ago but I forget what the resolution was and it seems to be happening in the current code.

```
http.js:35
  res.end(JSON.stringify(data, null, 2));
               ^

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Server.<anonymous> (http.js:35:16)
    at Server.emit (node:events:526:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by sethhall** [comment]
Ok, I found it...

```
// Interpret BigInt as simple number - do not use this unless
// you're okay loosing precision.
BigInt.prototype.toJSON = function() {
  return parseInt(this);
}
```

Any clue what the general solution to this might be?

**Comment by awelzel** [comment]
Rendering it as a string is the solution that will not loose precision, but need to have the consumer be aware of the conversion.

**Comment by sethhall** [comment]
Rendering as a string feels really wrong too.  It's not until rather large numbers that you start to lose precision.  I'd be inclined to make the snippet above a default behavior.  We could just document that very large numbers have reduced precision.  There just isn't much else we can realistically do about it unfortunately.

**Comment by awelzel** [comment]
>  I'd be inclined to make the snippet above a default behavior.

At this point, the toJSON can be set by a user. Would prefer not to have ZeekJS make this call - at least not by default. It might be worth documenting it better though.

I'll fix up the examples, they were from a time when Zeek's `count` type was lossy converted to `number`.

**Comment by sethhall** [comment]
If someone is working in typescript, this works...
```typescript
export interface BigInt {
    /** Convert to BigInt to string form in JSON.stringify */
    toJSON: () => number;
}

BigInt.prototype["toJSON"] = function (): number {
    return Number(this);
};
```

**Comment by awelzel** [comment]
> Sorry, I forgot to mention that this is running the http.js program in the examples.

I'm closing this - the `http.js` example is updated to render as string. It's the cheap way out, but it's up to the user to decide how to JSON serialize `BigInt`.
